
The following have been reloaded with a version change:
  1) python3/3.9.7 => python3/3.7.13

WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
  0%|          | 0/146 [00:00<?, ?it/s]  1%|          | 1/146 [00:00<00:42,  3.42it/s]  2%|▏         | 3/146 [00:00<00:16,  8.73it/s]  5%|▌         | 8/146 [00:00<00:06, 21.07it/s]  8%|▊         | 11/146 [00:00<00:07, 17.35it/s] 12%|█▏        | 17/146 [00:00<00:05, 24.73it/s] 14%|█▎        | 20/146 [00:01<00:07, 15.83it/s] 16%|█▌        | 23/146 [00:01<00:09, 13.17it/s] 21%|██        | 31/146 [00:01<00:05, 19.63it/s] 26%|██▌       | 38/146 [00:01<00:04, 26.37it/s] 29%|██▉       | 42/146 [00:02<00:04, 23.06it/s] 31%|███       | 45/146 [00:02<00:05, 20.15it/s] 33%|███▎      | 48/146 [00:02<00:05, 18.27it/s] 36%|███▋      | 53/146 [00:02<00:04, 22.79it/s] 41%|████      | 60/146 [00:02<00:02, 30.01it/s] 44%|████▍     | 64/146 [00:03<00:03, 21.63it/s] 46%|████▌     | 67/146 [00:03<00:04, 16.03it/s] 49%|████▊     | 71/146 [00:03<00:03, 19.15it/s] 51%|█████     | 74/146 [00:03<00:03, 19.62it/s] 56%|█████▌    | 82/146 [00:04<00:03, 19.44it/s] 60%|█████▉    | 87/146 [00:04<00:03, 17.83it/s] 64%|██████▍   | 94/146 [00:04<00:02, 22.12it/s] 66%|██████▋   | 97/146 [00:05<00:02, 18.49it/s] 69%|██████▉   | 101/146 [00:05<00:02, 21.51it/s] 71%|███████   | 104/146 [00:05<00:01, 21.54it/s] 74%|███████▍  | 108/146 [00:05<00:02, 17.87it/s] 76%|███████▌  | 111/146 [00:05<00:02, 15.50it/s] 79%|███████▉  | 116/146 [00:06<00:02, 14.16it/s] 84%|████████▍ | 123/146 [00:06<00:01, 20.07it/s] 86%|████████▋ | 126/146 [00:06<00:01, 16.86it/s] 89%|████████▉ | 130/146 [00:06<00:00, 17.66it/s] 94%|█████████▍| 137/146 [00:06<00:00, 25.45it/s] 97%|█████████▋| 141/146 [00:07<00:00, 23.49it/s]100%|██████████| 146/146 [00:07<00:00, 20.07it/s]
  0%|          | 0/147 [00:00<?, ?it/s]  1%|          | 1/147 [00:00<00:43,  3.33it/s]  2%|▏         | 3/147 [00:00<00:16,  8.53it/s]  4%|▍         | 6/147 [00:00<00:09, 14.67it/s]  8%|▊         | 12/147 [00:00<00:05, 25.47it/s] 12%|█▏        | 18/147 [00:00<00:03, 34.54it/s] 16%|█▌        | 23/147 [00:00<00:04, 29.44it/s] 20%|█▉        | 29/147 [00:01<00:03, 33.24it/s] 23%|██▎       | 34/147 [00:01<00:03, 36.89it/s] 27%|██▋       | 39/147 [00:01<00:03, 30.29it/s] 31%|███       | 45/147 [00:01<00:03, 30.28it/s] 35%|███▌      | 52/147 [00:01<00:02, 35.45it/s] 40%|████      | 59/147 [00:01<00:02, 40.09it/s] 44%|████▎     | 64/147 [00:03<00:08,  9.93it/s] 46%|████▋     | 68/147 [00:03<00:07, 10.87it/s] 50%|█████     | 74/147 [00:04<00:05, 12.71it/s] 55%|█████▌    | 81/147 [00:04<00:03, 17.85it/s] 58%|█████▊    | 85/147 [00:04<00:03, 19.36it/s] 61%|██████    | 89/147 [00:04<00:03, 18.89it/s] 63%|██████▎   | 93/147 [00:04<00:02, 21.68it/s] 67%|██████▋   | 99/147 [00:04<00:01, 27.79it/s] 70%|███████   | 103/147 [00:04<00:01, 27.98it/s] 73%|███████▎  | 108/147 [00:05<00:01, 29.93it/s] 78%|███████▊  | 114/147 [00:05<00:00, 33.02it/s] 82%|████████▏ | 120/147 [00:05<00:00, 38.05it/s] 85%|████████▌ | 125/147 [00:05<00:00, 32.73it/s] 88%|████████▊ | 130/147 [00:05<00:00, 33.31it/s] 91%|█████████ | 134/147 [00:05<00:00, 34.72it/s] 95%|█████████▍| 139/147 [00:05<00:00, 37.83it/s] 98%|█████████▊| 144/147 [00:05<00:00, 37.14it/s]100%|██████████| 147/147 [00:06<00:00, 24.41it/s]
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1501f653b4d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14cb5292a810>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14b5183fc850>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14ea836ef610>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x154ca4847790>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x152712a8f650>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14d2e9b0c690>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14a874990650>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x147ba36f8610>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x146200dc36d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14f4fe149610>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1493043e5710>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x15270b5b0fd0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14a4cb856650>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x146f61e876d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x146f520fc710>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x147da28e4610>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14ea7c1fa6d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14998cb96790>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14b975602590>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14b0957e57d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1466dc469650>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x148f5edb0390>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1469875e74d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x147544139650>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14fd795127d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x15320951c490>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x154acc5bc510>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14aa5651c4d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x149547d15790>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x152660482610>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14a4cc386490>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14b84734f7d0>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1526c2a64550>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x147c13bb9710>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x14e5d96c8590>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x152d0bfb3690>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
WARNING:root:The PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION variable should be set to "cpp".
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1479c5c55550>>, <Future finished exception=IndexError('list index out of range')>)
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "botgame_launcher_dipnet.py", line 163, in bot_loop
    return_obj = yield bot(rcvd_messages)
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/apps/intel19/python3/3.7.13/lib/python3.7/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 84, in __call__
    return super().__call__(rcvd_messages)
  File "/work/08801/wwongkam/ls6/baseline_bots/bots/pushover_bot.py", line 41, in __call__
    last_message = sorted_rcvd_messages[0]
IndexError: list index out of range
slurmstepd: error: *** JOB 246930 ON c305-022 CANCELLED AT 2022-06-21T00:42:21 ***
